# Page settings

BaseURL = "https://kpango.com/"
languageCode = "en-us"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-48533437-1"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    title = "Yusuke Kato Resume"
    description = "kpango (Yusuke Kato)'s resume site'"
    author = "Yusuke Kato"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it's quick and easy to change the styling and colour scheme.
    styles = "styles-6.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Yusuke Kato"
        tagline = "Technology Incubation (Lead Researcher of Vector Search)"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: kpango@vdaas.org"
        title = "kpango@vdaas.org"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+818067177951"
        title = "+818067177951"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//kpango.com"
        title = "kpango.com"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/yusuke-kato-aa992a115/"
        title = "linkedin.com/in/kpango"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/kpango"
        title = "github.com/kpango"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/kpang0"
        title = "@kpang0"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "BSc in Physics"
        college = "Tokai University"
        dates = "2012 - 2016"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "Japanese"
        level = "Native"

        [[params.language.list]]
        language = "English"
        level = "Conversational"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Building Home Network"

        [[params.interests.list]]
        interest = "Programming"

        [[params.interests.list]]
        interest = "Traveling"

        [[params.interests.list]]
        interest = "Cooking"

        [[params.interests.list]]
        interest = "Playing Badminton"

        [[params.interests.list]]
        interest = "Watching Movies"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "summary.md"

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experience"

        [[params.jobs.list]]
        position = "Technology Incubation"
        dates = "2019/8 - Present"
        company = "Yahoo Japan Corporation"
        details = "experiences/yahoo-techlab.md"

        [[params.jobs.list]]
        position = "SWAT (Senior Lead Developer)"
        dates = "2016/4 - 2019/8"
        company = "Yahoo Japan Corporation"
        details = "experiences/yahoo-swat.md"

        [[params.jobs.list]]
        position = "Go Language Technical Support Team"
        dates = "2016/11 - Present"
        company = "Yahoo Japan Corporation"
        details = "experiences/yahoo-go.md"

        [[params.jobs.list]]
        position = "HR Strategy"
        dates = "2017/1 - 2018/4"
        company = "Yahoo Japan Corporation"
        details = "experiences/yahoo-hr.md"

        [[params.jobs.list]]
        position = "Access Node Network Engineer Intern"
        dates = "2014/9 - 2014/11"
        company = "Softbank"
        details = "experiences/softbank.md"

        [[params.jobs.list]]
        position = "EC Site Backend Engineer Intern"
        dates = "2013/2 - 2014/10"
        company = "Nojima Corporation"
        details = "experiences/nojima.md"

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
        title = "Glg"
        url = "https://github.com/kpango/glg"
        tagline = "projects/glg.md"

        [[params.projects.list]]
        title = "Gache"
        url = "https://github.com/kpango/gache"
        tagline = "projects/gache.md"

        [[params.projects.list]]
        title = "Vald"
        url = "https://github.com/vdaas/vald"
        tagline = "projects/vald.md"

        [[params.projects.list]]
        title = "Garm"
        url = "https://github.com/yahoojapan/garm"
        tagline = "projects/garm.md"

        [[params.projects.list]]
        title = "Athenz Authorizer"
        url = "https://github.com/yahoojapan/athenz-authorizer"
        tagline = "projects/athenz-authorizer.md"

        [[params.projects.list]]
        title = "Athenz Authorization Proxy"
        url = "https://github.com/yahoojapan/authorization-proxy"
        tagline = "projects/authorization-proxy.md"

        [[params.projects.list]]
        title = "Athenz Client Sidecar"
        url = "https://github.com/yahoojapan/athenz-client-sidecar"
        tagline = "projects/athenz-client-sidecar.md"

        [[params.projects.list]]
        title = "NGTD"
        url = "https://github.com/yahoojapan/ngtd"
        tagline = "projects/ngtd.md"

        [[params.projects.list]]
        title = "gongt"
        url = "https://github.com/yahoojapan/gongt"
        tagline = "projects/gongt.md"

        [[params.projects.list]]
        title = "Gimbal"
        url = "https://github.com/heptio/gimbal"
        tagline = "projects/gimbal.md"

    # Projects section
    [params.awards]
        enable = true
        icon = "fa-trophy"
        title = "Awards"
        intro = "Awards such as Hackathon or Contest are below."

        [[params.awards.list]]
        title = "IPSJ Industrial Achievement Award 2019"
        url = "https://www.ipsj.or.jp/english/organization/aboutipsj/award/gyoseki.html"
        tagline = "awards/ipsj-iaa-2019.md"

        [[params.awards.list]]
        title = "Championship award at PwC's Technology Hackathon 2017"
        url = "https://www.facebook.com/PwCJapan/posts/1234088506626798"
        tagline = "awards/pwc-2017.md"

        [[params.awards.list]]
        title = "Championship award at SB Cloud Hackathon 2016"
        url = "https://www.facebook.com/SBCloud/photos/a.1092206347516664/1108994632504502/?type=1&theater"
        tagline = "awards/sbcloud-2016.md"

        [[params.awards.list]]
        title = "Second place at AngelHack JP 2016"
        url = "https://givery.co.jp/press/821/"
        tagline = "awards/angelhack-2016.md"

        [[params.awards.list]]
        title = "Technical award at HackU from Yahoo! Japan 2014"
        url = "https://hacku.yahoo.co.jp/tokai2014/"
        tagline = "awards/hacku-2014.md"

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Go"
        level = "95%"

        [[params.skills.list]]
        skill = "Java"
        level = "75%"

        [[params.skills.list]]
        skill = "PHP"
        level = "70%"

        [[params.skills.list]]
        skill = "Kotlin"
        level = "80%"

        [[params.skills.list]]
        skill = "C/C++"
        level = "75%"

        [[params.skills.list]]
        skill = "Nim"
        level = "60%"

        [[params.skills.list]]
        skill = "JavaScript & Vue.js (Nuxt.js)"
        level = "50%"

        [[params.skills.list]]
        skill = "SQL / RDB"
        level = "80%"

        [[params.skills.list]]
        skill = "Cassandra / CQL"
        level = "70%"

        [[params.skills.list]]
        skill = "Arch Linux"
        level = "80%"

        [[params.skills.list]]
        skill = "Kubernetes"
        level = "80%"

        [[params.skills.list]]
        skill = "OpenStack"
        level = "60%"

    [params.footer]
        copyright = "Yusuke Kato"
