# Page settings

BaseURL = "https://kpango.com/"
languageCode = "en-us"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    title = "Yusuke Kato Resume"
    description = "kpango (Yusuke Kato)'s resume site'"
    author = "Yusuke Kato"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-6.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Yusuke Kato"
        tagline = "SWAT (Expert Developer)"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: i.can.feel.gravity@gmail.com"
        title = "kpango@gmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+818067177951"
        title = "+818067177951"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//kpango.com"
        title = "kpango.com"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/yusuke-kato-aa992a115/"
        title = "linkedin.com/in/kpango"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/kpango"
        title = "github.com/kpango"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/kpang0"
        title = "@kpang0"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "BSc in Physics"
        college = "Tokai University"
        dates = "2012 - 2016"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "Japanese"
        level = "Native"

        [[params.language.list]]
        language = "English"
        level = "Conversational"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Programming"

        [[params.interests.list]]
        interest = "Travel"

        [[params.interests.list]]
        interest = "Cooking"

        [[params.interests.list]]
        interest = "Play Badminton"

        [[params.interests.list]]
        interest = "Movie"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "**Yahoo Japan Corporation**\n\n\n- ***kubernetes as a service authorization platform engineering & chief architect***\n\n  I developed\n\n- ***Approximate neighborhood graph tree vector search engine NGTD/Gongt engineering & quality engineer***\n\n  I developed\n\n- ***Yahoo online EBook store frontend engineering***\n\n  I developed\n\n- ***Inhouse A/B testing platform engineering & chief architect***\n\n  I developed\n\n- ***Yahoo premium member advertising platform engineering & chief architect***\n\n  I developed\n\n- ***Yahoo auction Android application engineering (Kotlin/Java)*** \n\n  I developed\n\n- ***Yahoo login platform backend engineering***\n\n  I developed\n\n- ***Yahoo mail backend engineering***\n\n\n\n**Softbank corporation**\n\n- ***Multi service access node network engineering at internship.***\n\n  I developed\n\n\n\n**R-Infinity Corporation**\n\n- ***adults game backend at internship***\n\n\n\n**Kojima Electronics Corporation**\n\n***EC site backend engineering at internship.***"
    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "SWAT (Expert Developer)"
        dates = "2016 - Present"
        company = "Yahoo Japan Corporation"
        details = "**Describe your role here**"

        [[params.jobs.list]]
        position = "Access Node Network Engineer"
        dates = "2014 - 2015"
        company = "Softbank"
        details = "**Describe your role here**"

        [[params.jobs.list]]
        position = "EC Site Backend Engineer"
        dates = "2013 - 2014"
        company = "Nojima Corporation"
        details = "**Describe your role here**"

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
        title = "Glg"
        url = "https://github.com/kpango/glg"
        tagline = "glg is faster than Go standard logger and provides leveled logging and colorized output option.\n\nGlg is used by many Yahoo Japan 's Go language platforms."

        [[params.projects.list]]
        title = "Gache"
        url = "https://github.com/kpango/gache"
        tagline = "gache is ultra fast lock-free cache library using concurrent map & xxhash algorithm.\n\nGache is used by many Yahoo Japan 's Go language platforms."

        [[params.projects.list]]
        title = "Garm"
        url = "https://github.com/yahoojapan/garm"
        tagline = "Garm is API for a Kubernetes authorization webhook that integrates with Athenz for access checks. It allows flexible resource mapping from K8s resources to Athenz ones.\n\nYahoo Japan uses Garm and Kubernetes AccessReview Webhook to integrate and manage hundreds of large Kubernetes clusters based on the concept of SSoT."

        [[params.projects.list]]
        title = "NGTD"
        url = "https://github.com/yahoojapan/ngtd"
        tagline = "NGTD is a VectorDatabase that provides approximate neighborhood search of dense vectors via REST / gRPC and is used as a core function of similar image search and recommendation engine of Yahoo Japan."

        [[params.projects.list]]
        title = "gongt"
        url = "https://github.com/yahoojapan/gongt"
        tagline = "Gongt is golang sdk for ngt core"

        [[params.projects.list]]
        title = "Gimbal"
        url = "https://github.com/heptio/gimbal"
        tagline = "Heptio Gimbal is an ingress load balancing platform capable of routing traffic to multiple Kubernetes and OpenStack clusters. Built by Heptio in partnership with Actapio & Yahoo Japan"

    # Projects section
    [params.awards]
        enable = true
        icon = "fa-trophy"
        title = "Awards"
        intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.awards.list]]
        title = "Championship award at PwC's Technology Hackathon 2017"
        url = ""
        tagline = ""

# Championship award at PwC's Technology Hackathon 2017
# 受賞日2017年1月  授与組織PwC

        [[params.awards.list]]
        title = "Championship award at SB Cloud Hackathon 2016"
        url = ""
        tagline = ""
# 賞の名称Championship award at SB Cloud Hackathon 2016
# 受賞日2016年7月  授与組織SoftBank

        [[params.awards.list]]
        title = "Second place at AngelHack JP 2016"
        url = ""
        tagline = ""
# 賞の名称Second place at AngelHack JP 2016
# 受賞日2016年5月  授与組織AngelHack

        [[params.awards.list]]
        title = "Technical award at HackU from Yahoo! Japan 2014"
        url = ""
        tagline = ""
# 賞の名称Technical award at HackU
# 受賞日2017年1月  授与組織Yahoo! JAPAN


    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Golang"
        level = "100%"

        [[params.skills.list]]
        skill = "Java"
        level = "90%"

        [[params.skills.list]]
        skill = "PHP"
        level = "85%"

        [[params.skills.list]]
        skill = "Kotlin"
        level = "80%"

        [[params.skills.list]]
        skill = "C/C++"
        level = "75%"

        [[params.skills.list]]
        skill = "Nim"
        level = "60%"

        [[params.skills.list]]
        skill = "JavaScript & Vue.js (Nuxt.js)"
        level = "50%"

        [[params.skills.list]]
        skill = "Kubernetes"
        level = "80%"

        [[params.skills.list]]
        skill = "OpenStack"
        level = "60%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    #projectprojectprojectprojectssss 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Yusuke Kato"
